library identifier: 'build-nodejs_nix@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'git@git@github.lbg.eu-gb.bluemix.net:jenkins-shared-library/build-nodejs_nix.git',
   credentialsId: 'ghe-credentials'])
   

pipeline {
  agent any  
    stages {
  	 stage('Checkout') {  
	     steps {
		checkout scm
	     }
         }
     stage('init') {
         steps {
           script {
         	 echo "Checking git workflow"
             String gitWorkFlow = gitWorkFlowTypeByBranchRule()
             echo "gitWorkFlow: ${gitWorkFlow}"
             env.branch = gitWorkFlow  
         	}
         }

      }
     stage('build') {
         steps {
	    runNpm("npm")
	    runNpm("npm run")
	    runNpmPackage( env.branch ) 
	     }
	     } 	
          }
    }
